version: '3.8'

services:
  eeg-data-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eeg-task-data-server:latest
    container_name: eeg-task-data-server
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config.yml:/app/config.yml
    environment:
      - EEG_SENTRY_ENVIRONMENT=docker
    restart: unless-stopped